In [1]:
import requests
import pandas as pd
import time
from geopy.geocoders import Nominatim
import folium
import numpy as np

import pandas as pd
from sklearn.cluster import SpectralClustering
from sklearn.metrics.pairwise import haversine_distances
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
from shapely.geometry import Point
from sklearn.cluster import DBSCAN

# Functions

In [ ]:
# Variables

lat_max = 43.449957
lat_min = 42.905523
long_max = -1.699531
long_min = -2.597522

api_key = 'AIzaSyABi4H4yNaD3i14rlhGoaHyiuCUXfIqi8w'

df_towns = pd.read_excel(f'input_data/town_coordinates.xlsx')

In [ ]:
# Function 1: Find the coordinates of an address using the Google Maps Geocoding API

def geocode_address(address, api_key):
    base_url = "https://maps.googleapis.com/maps/api/geocode/json"

    params = {
        "address": address,
        "key": api_key
    }

    response = requests.get(base_url, params=params)

    if response.status_code == 200:
        # Convierte la respuesta en un objeto JSON
        data = response.json()

        if data['status'] == 'OK':
            results = data['results'][0]
            location = results['geometry']['location']
            return location['lat'], location['lng']
        else:
            # print(f"Error en la solicitud: {data['status']}")
            return None, None  # Retorna None en caso de error
    else:
        print(f"Error en la solicitud HTTP: {response.status_code}")
        return None, None  # Retorna None en caso de error

In [ ]:
# Function 2: Verify that the coordinates are correct according to the two conditions, and return the correct and incorrect dataframes.
    # Condition 1: The coordinates must be within the limits of Gipuzkoa
    # Condition 2: The coordinates must be within a radius of 5 km from the town center of the municipality to which the establishment belongs. This is done because is has been detected that some streets are repeated in different towns and the API confuses them (for example, Arrasate Kalea 8 can be in many towns). To calculate the distance, I will use the Haversine formula, which calculates the distance between two points on the Earth given their latitude and longitude

def verify_latlong(df):
    # Condition 1
    for index, row in df.iterrows():
        if row['lat'] < lat_min or row['lat'] > lat_max or row['long'] < long_min or row['long'] > long_max:
            df.at[index, 'lat'] = None
            df.at[index, 'long'] = None
    
    # Condition 2

    R = 6371.0

    df['lat_establishment_rad'] = np.radians(df['lat'])
    df['lon_establishment_rad'] = np.radians(df['long'])
    df['lat_town_rad'] = np.radians(df['latitud'])
    df['lon_town_rad'] = np.radians(df['longitud'])

    df['delta_lat'] = df['lat_town_rad'] - df['lat_establishment_rad']
    df['delta_lon'] = df['lon_town_rad'] - df['lon_establishment_rad']

    # Fórmula del Haversine para todas las filas
    a = np.sin(df['delta_lat'] / 2)**2 + np.cos(df['lat_establishment_rad']) * np.cos(df['lat_town_rad']) * np.sin(df['delta_lon'] / 2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

    df['distancia_km'] = R * c
    df = df.drop(columns = ['lat_establishment_rad', 'lon_establishment_rad', 'lat_town_rad', 'lon_town_rad', 'delta_lat', 'delta_lon'])

    for index, row in df.iterrows():
        if row['distancia_km'] >= 5:
            df.at[index, 'lat'] = None
            df.at[index, 'long'] = None

    df_1 = df[df['lat'].notna()]
    df_2 = df[df['lat'].isna()]
    
    return df_1, df_2

In [ ]:
# Function 3: Couple the previous two functions. First look for the lat,long with Google Maps (F1), then verify with the two conditions (F2) and then look again for lat,long for the incorrect ones with OSM. Finally, verify again with F2.

def function_latlong(df):

    # Calculate lat,long with Google Maps
    latitudes = []
    longitudes = []
    # print(len(df))
    for index, address in enumerate(df['address']):
        lat, long = geocode_address(address, api_key)
        latitudes.append(lat)
        longitudes.append(long)

        if index%1000==0:
            print(index, lat, long)

    df['lat'] = latitudes
    df['long'] = longitudes

    print('Finished GMaps')

    # Dividir el df en satisfactorio y no satisfactorio
    df_gm_mal = df[df['lat'].isna()]
    df_gm_bien = df[df['lat'].notna()]

    # Una vez calculado, ver si df_gm_bien cumple con los requisitos
    df_gm_bien_bien, df_gm_bien_mal = verify_latlong(df_gm_bien)

    # Crear el df para pasarselo a OSM
    df_osm = pd.concat([df_gm_mal, df_gm_bien_mal])

    # Calculate lat,long with OSM
    geolocator = Nominatim(user_agent="my_user_agent")

    for index, row in df_osm.iterrows():
        # if pd.isna(row['lat']):
            address = row['address']
            try:
                loc = geolocator.geocode(address)
                if loc is not None:
                    df_osm.at[index, 'lat'] = loc.latitude
                    df_osm.at[index, 'long'] = loc.longitude
            except AttributeError:
                print(f"Error: Could not retrieve location for address: {address}")
    
    print('Finished OSM')

    # Dividir el df en satisfactorio y no satisfactorio
    df_osm_mal = df_osm[df_osm['lat'].isna()]
    df_osm_bien = df_osm[df_osm['lat'].notna()]

    # Una vez calculado, ver si df_osm_bien cumple con los requisitos
    df_osm_bien_bien, df_osm_bien_mal = verify_latlong(df_osm_bien)

    # Terminado, ahora creo los dos dfs, el satisfactorio y el no satisfactorio

    df_correcto = pd.concat([df_gm_bien_bien, df_osm_bien_bien])
    df_incorrecto = pd.concat([df_osm_mal, df_osm_bien_mal])

    return df_correcto, df_incorrecto

# Code

First, upload the establishments file and make any necessary adjustments before calculating the latitude and longitude coordinates.

Then, run the main block and follow these steps:

1. Run Function 3 and save the outputs as:
   - `paso_1_correcto`
   - `paso_1_incorrecto`

2. Modify addresses for a different input (change to Euskera) and repeat the process to generate:
   - `paso_2_correcto`
   - `paso_2_incorrecto`

3. Modify addresses for a different input (use the establishment name instead of the address) and repeat the process to generate:
   - `paso_3_correcto`
   - `paso_3_incorrecto`

4. Merge the following DataFrames (paso_3_incorrecto will be the only establilshments without proper lat,longs):
   - `paso_1_correcto`
   - `paso_2_correcto`
   - `paso_3_correcto`

In [ ]:
establishments = pd.read_excel(f'input_data/raw_data.xlsx', engine='openpyxl')
establishments = establishments.drop(columns=['Unnamed: 0', 'Unnamed: 8'])
establishments.head()

In [ ]:
establishments['address'] = establishments['DIRECCIÓN'] + ', ' + establishments['MUNICIPIO']
establishments = pd.merge(establishments, df_towns, left_on = 'MUNICIPIO', right_on = 'Town', how = 'inner')

establishments

In [ ]:
# Call function for STEP 1
print('The length of the STEP 1 df is: ' + str(len(establishments)))
paso_1_correcto, paso_1_incorrecto = function_latlong(establishments)
print('Length paso_1_correcto: ' + str(len(paso_1_correcto)) + ' and Length paso_1_incorrecto: ' + str(len(paso_1_incorrecto)))
paso_1_correcto.to_excel(f'output_data/aux_files/paso_1_correcto.xlsx', index=False)
paso_1_incorrecto.to_excel(f'output_data/aux_files/paso_1_incorrecto.xlsx', index=False)

# Change 1
df_calle = paso_1_incorrecto[paso_1_incorrecto['address'].str.contains('calle', case=False, na=False)].reset_index(drop=True)
df_barrio = paso_1_incorrecto[paso_1_incorrecto['address'].str.contains('barrio', case=False, na=False)].reset_index(drop=True)
df_avenida = paso_1_incorrecto[paso_1_incorrecto['address'].str.contains('avenida', case=False, na=False)].reset_index(drop=True)
df_plaza = paso_1_incorrecto[paso_1_incorrecto['address'].str.contains('plaza', case=False, na=False)].reset_index(drop=True)
df_paseo = paso_1_incorrecto[paso_1_incorrecto['address'].str.contains('paseo', case=False, na=False)].reset_index(drop=True)
df_pol = paso_1_incorrecto[paso_1_incorrecto['address'].str.contains('pol', case=False, na=False)].reset_index(drop=True)
df_diseminado = paso_1_incorrecto[paso_1_incorrecto['address'].str.contains('diseminado', case=False, na=False)].reset_index(drop=True)
df_nucleo = paso_1_incorrecto[paso_1_incorrecto['address'].str.contains('núcleo', case=False, na=False)].reset_index(drop=True)
df_restantes = paso_1_incorrecto[~paso_1_incorrecto['address'].str.contains('calle|barrio|avenida|plaza|paseo|pol|diseminado|núcleo', case=False, na=False)].reset_index(drop=True)

df_calle['address'] = df_calle['address'].str.replace(r'\bcalle\b\s+([^,]+),', r'\1 Kalea,', case=False, regex=True)
df_barrio['address'] = df_barrio['address'].str.replace(r'\bbarrio\b\s+([^,]+),', r'\1 Auzoa,', case=False, regex=True)
df_avenida['address'] = df_avenida['address'].str.replace(r'\bavenida\b\s+([^,]+),', r'\1 Etorbidea,', case=False, regex=True)
df_plaza['address'] = df_plaza['address'].str.replace(r'\bplaza\b\s+([^,]+),', r'\1 Enparantza,', case=False, regex=True)
df_paseo['address'] = df_paseo['address'].str.replace(r'\bpaseo\b\s+([^,]+),', r'\1 Pasealekua,', case=False, regex=True)
df_pol['address'] = df_pol['DENOMINACIÓN DEL ESTABLECIMIENTO'] + ', ' + df_pol['MUNICIPIO']
df_diseminado['address'] = df_diseminado['DENOMINACIÓN DEL ESTABLECIMIENTO'] + ', ' + df_diseminado['MUNICIPIO']
df_nucleo['address'] = df_nucleo['DENOMINACIÓN DEL ESTABLECIMIENTO'] + ', ' + df_nucleo['MUNICIPIO']
df_restantes['address'] = df_restantes['DENOMINACIÓN DEL ESTABLECIMIENTO'] + ', ' + df_restantes['MUNICIPIO']

paso_1_incorrecto = pd.concat([df_calle, df_barrio, df_avenida, df_plaza, df_paseo, df_pol, df_diseminado, df_nucleo, df_restantes])

#------------------------------%%%%%%%%%%%%%%%%%%%%%%%%%%----------------------------------

# Call function  for STEP 2
print('The length of the STEP 2 df is: ' + str(len(paso_1_incorrecto)))
paso_2_correcto, paso_2_incorrecto = function_latlong(paso_1_incorrecto)
print('Length paso_2_correcto: ' + str(len(paso_2_correcto)) + ' and Length paso_2_incorrecto: ' + str(len(paso_2_incorrecto)))
paso_2_correcto.to_excel(f'output_data/aux_files/paso_2_correcto.xlsx', index=False)
paso_2_incorrecto.to_excel(f'output_data/aux_files/paso_2_incorrecto.xlsx', index=False)

# Change 2
df_calle = paso_2_incorrecto[paso_2_incorrecto['address'].str.contains('calle', case=False, na=False)].reset_index(drop=True)
df_barrio = paso_2_incorrecto[paso_2_incorrecto['address'].str.contains('barrio', case=False, na=False)].reset_index(drop=True)
df_avenida = paso_2_incorrecto[paso_2_incorrecto['address'].str.contains('avenida', case=False, na=False)].reset_index(drop=True)
df_plaza = paso_2_incorrecto[paso_2_incorrecto['address'].str.contains('plaza', case=False, na=False)].reset_index(drop=True)
df_paseo = paso_2_incorrecto[paso_2_incorrecto['address'].str.contains('paseo', case=False, na=False)].reset_index(drop=True)
df_pol = paso_2_incorrecto[paso_2_incorrecto['address'].str.contains('pol', case=False, na=False)].reset_index(drop=True)
df_diseminado = paso_2_incorrecto[paso_2_incorrecto['address'].str.contains('diseminado', case=False, na=False)].reset_index(drop=True)
df_nucleo = paso_2_incorrecto[paso_2_incorrecto['address'].str.contains('núcleo', case=False, na=False)].reset_index(drop=True)
df_restantes = paso_2_incorrecto[~paso_2_incorrecto['address'].str.contains('calle|barrio|avenida|plaza|paseo|pol|diseminado|núcleo', case=False, na=False)].reset_index(drop=True)

df_calle['address'] = df_calle['DENOMINACIÓN DEL ESTABLECIMIENTO'] + ', ' + df_calle['MUNICIPIO']
df_barrio['address'] = df_barrio['DENOMINACIÓN DEL ESTABLECIMIENTO'] + ', ' + df_barrio['MUNICIPIO']
df_avenida['address'] = df_avenida['DENOMINACIÓN DEL ESTABLECIMIENTO'] + ', ' + df_avenida['MUNICIPIO']
df_plaza['address'] = df_plaza['DENOMINACIÓN DEL ESTABLECIMIENTO'] + ', ' + df_plaza['MUNICIPIO']
df_paseo['address'] = df_paseo['DENOMINACIÓN DEL ESTABLECIMIENTO'] + ', ' + df_paseo['MUNICIPIO']
df_pol['address'] = df_pol['DENOMINACIÓN DEL ESTABLECIMIENTO'] + ', ' + df_pol['MUNICIPIO']
df_diseminado['address'] = df_diseminado['DENOMINACIÓN DEL ESTABLECIMIENTO'] + ', ' + df_diseminado['MUNICIPIO']
df_nucleo['address'] = df_nucleo['DENOMINACIÓN DEL ESTABLECIMIENTO'] + ', ' + df_nucleo['MUNICIPIO']
df_restantes['address'] = df_restantes['DENOMINACIÓN DEL ESTABLECIMIENTO'] + ', ' + df_restantes['MUNICIPIO']

paso_2_incorrecto = pd.concat([df_calle, df_barrio, df_avenida, df_plaza, df_paseo, df_pol, df_diseminado, df_nucleo, df_restantes])

#------------------------------%%%%%%%%%%%%%%%%%%%%%%%%%%----------------------------------

# Call function  for STEP 3
print('The length of the STEP 3 df is: ' + str(len(paso_2_incorrecto)))
paso_3_correcto, paso_3_incorrecto = function_latlong(paso_2_incorrecto)
print('Length paso_3_correcto: ' + str(len(paso_3_correcto)) + ' and Length paso_3_incorrecto: ' + str(len(paso_3_incorrecto)))
paso_3_correcto.to_excel(f'output_data/aux_files/paso_3_correcto.xlsx', index=False)
paso_3_incorrecto.to_excel(f'output_data/aux_files/paso_3_incorrecto.xlsx', index=False)

# Last step, concatenate dfs
df_establishments_correcto = pd.concat([paso_1_correcto, paso_2_correcto, paso_3_correcto])
df_establishments_incorrecto = paso_3_incorrecto
print('Length df_establishments_correcto: ' + str(len(df_establishments_correcto)) + ' and Length df_establishments_incorrecto: ' + str(len(df_establishments_incorrecto)))
df_establishments_correcto.to_excel(f'output_data/aux_files/df_establishments_correcto.xlsx', index=False)
df_establishments_incorrecto.to_excel(f'output_data/aux_files/df_establishments_incorrecto.xlsx', index=False)

In [ ]:
df_establishments = pd.concat([df_establishments_correcto, df_establishments_incorrecto])
df_establishments.to_excel('output_data/df_establishments_latlong.xlsx', index=False)
len(df_establishments)

56038

In [ ]:
# Assign the maximum number of workers to each establishment according to the "ESTRATO EMPLEO" column, which is a categorical variable with the following values: '<=2', '3-5', '6-9', '10-14', '15-19', '20-49', '50-99', '100-249', '250-499', '>=500'. For example, if the value is '3-5', the maximum number of workers will be 5. If the value is '>=500', the maximum number of workers will be 500.

def asignar_trabajdores(valor):
    if valor == '<=2':
        return 2
    if valor == '3-5':
        return 5
    if valor == '6-9':
        return 9
    if valor == '10-14':
        return 14
    if valor == '15-19':
        return 19
    if valor == '20-49':
        return 49
    if valor == '50-99':
        return 99
    if valor == '100-249':
        return 249
    if valor == '250-499':
        return 499
    if valor == '>=500':
        return 500
    
df_establishments['num_workers'] = df_establishments['ESTRATO EMPLEO'].apply(asignar_trabajdores)

Now, for the big establishments without a proper lat,long (21 in total), I manually assign the latlong.

In [68]:
# Big establishments without coordinates

df_filtered = df_establishments_incorrecto.loc[
    (df_establishments_incorrecto['ESTRATO EMPLEO'] == '>=500') |
    (df_establishments_incorrecto['ESTRATO EMPLEO'] == '250-499') |
    (df_establishments_incorrecto['ESTRATO EMPLEO'] == '100-249') |
    (df_establishments_incorrecto['ESTRATO EMPLEO'] == '50-99') |
    (df_establishments_incorrecto['ESTRATO EMPLEO'] == '20-49') |
    (df_establishments_incorrecto['ESTRATO EMPLEO'] == '15-19')
]
df_filtered

,IDENTIFICADOR,DENOMINACIÓN DEL ESTABLECIMIENTO,DIRECCIÓN,LOCALIDAD,CÓD. POSTAL,MUNICIPIO,TERRITORIO HISTÓRICO,CNAE,DESCRIPCIÓN CNAE,ESTRATO EMPLEO,AÑO DE REFERENCIA,address,lat,long,Town,latitud,longitud,distancia_km
70,L0114142,Somapel,"Pol. Indus. Azketaerreka, 7",Villabona,20150,Villabona,Gipuzkoa,5224,Manipulación de mercancías,15-19,2023,"Somapel, Villabona",NaN,NaN,Villabona,43.186929,-2.052548,21.941040
80,L0181801,Acabados Laiz,"Pol. Indus. Ubegun, 9",Ubegun Industrigunea,20810,Aia,Gipuzkoa,2561,Tratamiento y revestimiento de metales,20-49,2023,"Acabados Laiz, Aia",NaN,NaN,Aia,43.236838,-2.148641,23.164644
81,L0430738,Ondo Metal,"Pol. Indus. Ubegun, 9",Ubegun Industrigunea,20810,Aia,Gipuzkoa,2529,"Fabricación de otras cisternas, grandes depósi...",20-49,2023,"Ondo Metal, Aia",NaN,NaN,Aia,43.236838,-2.148641,25.512687
90,L0502475,Metalder,"Diseminado Segura, 26",Segura,20214,Segura,Gipuzkoa,2562,Ingeniería mecánica por cuenta de terceros,20-49,2023,"Metalder, Segura",NaN,NaN,Segura,43.007853,-2.253132,37.328581
405,L0418634,Pesca marina,"Barrio Santio Erreka, 43",Santio Erreka,20810,Aia,Gipuzkoa,311,Pesca marina,20-49,2023,"Pesca marina, Aia",NaN,NaN,Aia,43.236838,-2.148641,10.986383
319,L0045715,Garrai,"Calle Apaor, 8",Zubieta,20160,Donostia / San Sebastián,Gipuzkoa,4941,Transporte de mercancías por carretera,20-49,2023,"Garrai, Donostia / San Sebastián",NaN,NaN,Donostia / San Sebastián,43.318237,-1.981705,8.209215
456,L0101158,Gure Zura,"Barrio Eizagirre, 314",Azpeitia,20738,Azpeitia,Gipuzkoa,1610,Aserrado y cepillado de la madera,20-49,2023,"Gure Zura, Azpeitia",NaN,NaN,Azpeitia,43.182598,-2.266732,6.276605
505,L0066858,Desguaces Vidaurreta,"Barrio Jaitzubia, 141",Jaitzubia,20280,Hondarribia,Gipuzkoa,4677,Comercio al por mayor de chatarra y productos ...,20-49,2023,"Desguaces Vidaurreta, Hondarribia",NaN,NaN,Hondarribia,43.368603,-1.799811,5.241208
695,L0452161,Las Habitaciones de Akelarre,"Paseo Padre Orkolaga, 56",Igeldo,20008,Donostia / San Sebastián,Gipuzkoa,5510,Hoteles y alojamientos similares,15-19,2023,"Las Habitaciones de Akelarre, Donostia / San S...",NaN,NaN,Donostia / San Sebastián,43.318237,-1.981705,5.104315
707,L0113198,Academia de Cocina Akelarre,"Paseo Padre Orkolaga, 56",Igeldo,20008,Donostia / San Sebastián,Gipuzkoa,8559,Otra educación n.c.o.p.,20-49,2023,"Academia de Cocina Akelarre, Donostia / San Se...",NaN,NaN,Donostia / San Sebastián,43.318237,-1.981705,5.104315
716,L0487151,Saltoki Donostia-Zubieta,"Paseo Arrapide, 77",Zubieta,20160,Donostia / San Sebastián,Gipuzkoa,4673,"Comercio al por mayor de madera, materiales de...",15-19,2023,"Saltoki Donostia-Zubieta, Donostia / San Sebas...",NaN,NaN,Donostia / San Sebastián,43.318237,-1.981705,7.767268
730,L0427456,Bugati Erretegia,"Paseo Arrapide, 74",Zubieta,20160,Donostia / San Sebastián,Gipuzkoa,5610,Restaurantes y puestos de comidas,15-19,2023,"Bugati Erretegia, Donostia / San Sebastián",NaN,NaN,Donostia / San Sebastián,43.318237,-1.981705,7.601495
769,L0272216,Sociedad de Cartera de Zestoa,"Polígono Industrialdea, A-1",Itziar,20829,Deba,Gipuzkoa,8299,Otras actividades de apoyo a las empresas n.c....,15-19,2023,"Sociedad de Cartera de Zestoa, Deba",NaN,NaN,Deba,43.296302,-2.352369,9.737779
828,L0511954,Jamai Technical Service,"Pol. Indus. Errota, 4-C",Anoeta,20270,Anoeta,Gipuzkoa,2451,Fundición de hierro,15-19,2023,"Jamai Technical Service, Anoeta",NaN,NaN,Anoeta,43.162138,-2.070734,5.163149
927,L0021348,CPEIPS La Anunciata HLBHIP,"Camino Lorete, 2",Donostia / San Sebastián,20017,Donostia / San Sebastián,Gipuzkoa,8520,Educación primaria,50-99,2023,"CPEIPS La Anunciata HLBHIP, Donostia / San Seb...",NaN,NaN,Donostia / San Sebastián,43.318237,-1.981705,5.001058
968,L0057400,Restaurante Sidrería Araeta,"Camino Berridi, 22",Zubieta,20160,Donostia / San Sebastián,Gipuzkoa,5610,Restaurantes y puestos de comidas,15-19,2023,"Restaurante Sidrería Araeta, Donostia / San Se...",NaN,NaN,Donostia / San Sebastián,43.318237,-1.981705,6.650655
262,L0021024,Centro de Salud Pasai Antxo,"Calle Eskalantegi, 68",Donostia / San Sebastián,20017,Donostia / San Sebastián,Gipuzkoa,8621,Actividades de medicina general,15-19,2023,"Centro de Salud Pasai Antxo, Donostia / San Se...",NaN,NaN,Donostia / San Sebastián,43.318237,-1.981705,5.073950
299,L0100364,Decathlon,"Calle Fernando Múgica, 2",Donostia / San Sebastián,20018,Donostia / San Sebastián,Gipuzkoa,4764,Comercio al por menor de artículos deportivos ...,50-99,2023,"Decathlon, Donostia / San Sebastián",NaN,NaN,Donostia / San Sebastián,43.318237,-1.981705,5.004970
301,L0434604,Mercadona,"Calle Fernando Múgica, 1",Donostia / San Sebastián,20018,Donostia / San Sebastián,Gipuzkoa,4711,Comercio al por menor en establecimientos no e...,50-99,2023,"Mercadona, Donostia / San Sebastián",NaN,NaN,Donostia / San Sebastián,43.318237,-1.981705,5.047842
705,L0026754,Restaurante Akelarre,"Paseo Padre Orkolaga, 56",Igeldo,20008,Donostia / San Sebastián,Gipuzkoa,5610,Restaurantes y puestos de comidas,20-49,2023,"Restaurante Akelarre, Donostia / San Sebastián",NaN,NaN,Donostia / San Sebastián,43.318237,-1.981705,5.105747
725,L0238837,Hipódromo de San Sebastián,"Paseo Arrapide, 11",Zubieta,20160,Donostia / San Sebastián,Gipuzkoa,9311,Gestión de instalaciones deportivas,20-49,2023,"Hipódromo de San Sebastián, Donostia / San Seb...",NaN,NaN,Donostia / San Sebastián,43.318237,-1.981705,7.036766

In [ ]:
# Assign latlong to these establishments

df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0114142'), ['lat', 'long']] = [43.17707573691162, -2.0561387576716337]
df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0181801'), ['lat', 'long']] = [43.27203241010077, -2.1304903511094047]
df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0430738'), ['lat', 'long']] = [43.271324559678135, -2.1319124734322483]
df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0502475'), ['lat', 'long']] = [43.0092759285847, -2.2543479530703787]
df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0418634'), ['lat', 'long']] = [43.26684338819905, -2.1183556325991484]
df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0045715'), ['lat', 'long']] = [43.25125677528691, -2.0241051501055463]
df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0101158'), ['lat', 'long']] = [43.13217733307857, -2.231845654751211]
df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0066858'), ['lat', 'long']] = [43.333001065496795, -1.8422952815487512]
df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0452161'), ['lat', 'long']] = [43.30746383362821, -2.044012610821045]
df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0113198'), ['lat', 'long']] = [43.30746383362821, -2.044012610821045]
df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0487151'), ['lat', 'long']] = [43.2549495376769, -2.0223752815576943]
df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0427456'), ['lat', 'long']] = [43.25624621120414, -2.0213207797825583]
df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0272216'), ['lat', 'long']] = [43.276463009546234, -2.3376585905364426]
df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0511954'), ['lat', 'long']] = [43.16154743908465, -2.071766976839273]
df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0021348'), ['lat', 'long']] = [43.318240939874435, -1.919881298463976]
df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0057400'), ['lat', 'long']] = [43.27021451181457, -2.030773510587201]
df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0021024'), ['lat', 'long']] = [43.3154134755984, -1.9190392370711713]
df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0100364'), ['lat', 'long']] = [43.2798115819425, -2.0136707648517636]
df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0434604'), ['lat', 'long']] = [43.28082421633482, -2.017139886867962]
df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0026754'), ['lat', 'long']] = [43.307744131589, -2.0431100037190193]
df_establishments.loc[(df_establishments['IDENTIFICADOR'] == 'L0238837'), ['lat', 'long']] = [43.26539109327641, -2.0245725482699806]

df_establishments.to_excel(f'output_data/df_establishments_latlong.xlsx', index=False)
df_establishments.to_csv(f'output_data/df_establishments_latlong.csv', index=False)

In [7]:
df_establishments

,IDENTIFICADOR,DENOMINACIÓN DEL ESTABLECIMIENTO,DIRECCIÓN,LOCALIDAD,CÓD. POSTAL,MUNICIPIO,TERRITORIO HISTÓRICO,CNAE,DESCRIPCIÓN CNAE,ESTRATO EMPLEO,...,lat,long,Town,latitud,longitud,distancia_km,max_num_workers,num_workers,Unnamed: 20,Unnamed: 21
0,L0453049,Agricultura y ganadería,"Barrio Sasiain-Arandi, 1",Abaltzisketa,20269,Abaltzisketa,Gipuzkoa,150,Producción agrícola combinada con la producció...,<=2,...,43.048444,-2.105448,Abaltzisketa,43.048444,-2.105448,0.000000,2,1,NaN,NaN
1,L0027051,Ayuntamiento Abaltzisketa,"Núcleo Abaltzisketa, 11",Abaltzisketa,20269,Abaltzisketa,Gipuzkoa,8411,Actividades generales de la administración púb...,6-9,...,43.048444,-2.105448,Abaltzisketa,43.048444,-2.105448,0.000000,9,6,NaN,315408.0
2,L0305841,"Secane Estevez, Rd","Núcleo Abaltzisketa, 30-6",Abaltzisketa,20269,Abaltzisketa,Gipuzkoa,4941,Transporte de mercancías por carretera,<=2,...,43.048444,-2.105448,Abaltzisketa,43.048444,-2.105448,0.000000,2,2,NaN,NaN
3,L0304237,Cría de ovinos y caprinos,"Barrio Azaldegi-Estanga, 9",Abaltzisketa,20269,Abaltzisketa,Gipuzkoa,145,Explotación de ganado ovino y caprino,<=2,...,43.048444,-2.105448,Abaltzisketa,43.048444,-2.105448,0.000000,2,2,NaN,NaN
4,L0528240,Traducción,"Núcleo Abaltzisketa, 8",Abaltzisketa,20269,Abaltzisketa,Gipuzkoa,7430,Actividades de traducción e interpretación,<=2,...,43.048444,-2.105448,Abaltzisketa,43.048444,-2.105448,0.000000,2,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56033,L0494604,Restaurante Zaldua,"Paseo Arrapide, 8",Zubieta,20160,Donostia / San Sebastián,Gipuzkoa,5610,Restaurantes y puestos de comidas,3-5,...,NaN,NaN,Donostia / San Sebastián,43.318237,-1.981705,6.745887,5,5,NaN,NaN
56034,L0238837,Hipódromo de San Sebastián,"Paseo Arrapide, 11",Zubieta,20160,Donostia / San Sebastián,Gipuzkoa,9311,Gestión de instalaciones deportivas,20-49,...,43.265391,-2.024573,Donostia / San Sebastián,43.318237,-1.981705,7.036766,49,23,NaN,NaN
56035,L0303369,Vaquería,"Diseminado Segura, 38",Segura,20214,Segura,Gipuzkoa,141,Explotación de ganado bovino para la producció...,<=2,...,NaN,NaN,Segura,43.007853,-2.253132,NaN,2,1,NaN,NaN
56036,L0368227,Vaquería,"Diseminado Segura, 39",Segura,20214,Segura,Gipuzkoa,142,Explotación de otro ganado bovino y búfalos,<=2,...,NaN,NaN,Segura,43.007853,-2.253132,NaN,2,1,NaN,NaN
56037,L0291187,Restaurante Susperregi,"Lugar Aldura, 62",Zona Aldura,20100,Errenteria,Gipuzkoa,5630,Establecimientos de bebidas,<=2,...,NaN,NaN,Errenteria,43.308111,-1.891282,5.488939,2,1,NaN,NaN

In [ ]:
# Create shapefile

# Crear geometría
geometry = gpd.points_from_xy(
    df_establishments['longitud'],
    df_establishments['latitud']
)

# Convertir a GeoDataFrame
gdf_establishments = gpd.GeoDataFrame(
    df_establishments,
    geometry=geometry,
    crs='EPSG:4326'
)

gdf_establishments.to_file(f'output_data/establishments/establishments.shp')

Generate a visualization

In [ ]:
# Percentage of Gipuzkoan employees without lat,long

suma_yes = df_establishments[df_establishments['lat'].notna()]['num_workers'].sum()
suma_no = df_establishments[df_establishments['lat'].isna()]['num_workers'].sum()
suma = df_establishments['num_workers'].sum()
# print(suma, suma_yes, suma_no)
trabajadores_no_representados = (suma_no*100/suma)
print("Percentage of workers without lat,long: " + str(trabajadores_no_representados))

# Number of df_establishments without lat,long

num = df_establishments['lat'].isna().sum()
print("Number of establishments without lat,long: " + str(num))

Porcentaje de trabajadores sin lat,long: 0.23696187489991205
Numero de establecimientos sin lat,long: 312

In [8]:
df_establishments['ESTRATO EMPLEO'].value_counts()
df_establishments['num_workers'].value_counts()

num_workers
2      20046
1      19835
3       2659
4       2623
5       2617
       ...
334        1
122        1
114        1
410        1
416        1
Name: count, Length: 276, dtype: int64

In [ ]:
# # Show establishments

# map_center = [df_establishments['lat'].mean(), df_establishments['long'].mean()]
# mymap = folium.Map(location=map_center, zoom_start=12)

# # Añadir círculos al mapa
# for index, row in df_establishments.iterrows():
#     if pd.notna(row['lat']) and pd.notna(row['long']):
#         folium.CircleMarker(
#             location=[row['lat'], row['long']],
#             radius=row['num_workers'] / 10,  # Ajustar tamaño del círculo proporcional al valor
#             color='blue',
#             fill=True,
#             fill_color='blue'
#         ).add_to(mymap)

# # Guardar el mapa como HTML
# mymap.save("mapa_con_circulos.html")